name: what_to_wear_today
description: Hyper-local outfit recommendations powered by Supabase.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  supabase_flutter: ^2.5.4
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  intl: ^0.20.2
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/tops/
    - assets/images/bottoms/
    - assets/images/outers/
    - assets/images/shoes/
    - assets/images/accessories/
    - assets/images/tops/tshirt.svg
